### ISSUE TITLE
Doesn't work with the latest version of AdonisJS

### ISSUE THREAD

**Issue by MichaelNZ85** [Shagital/adonisjs-crud-generator#1]
I have been unable to get this package to work with the current version of AdonisJS (5.4.2). The Adonis CLI is largely deprecated, and this package relies on it to setup the CRUD infrastructure behind the scenes.

Would it be possible to make this project work with the current version of AdonisJS?

**Comment by djunehor** [comment]
The next major version will be compatible with AdonisJS 5. A PR is also welcome

**Comment by djunehor** [comment]
https://github.com/Shagital/adonisjs-crud-generator/releases/tag/3.0.3
