### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by a7mdragab** [Shagital/adonisjs-crud-generator#2]
Please update to adonisjs 5

**Comment by djunehor** [comment]
Please [see](https://github.com/Shagital/adonisjs-crud-generator/issues/1#issuecomment-1055574424)

**Comment by a7mdragab** [comment]
> Please [see](https://github.com/Shagital/adonisjs-crud-generator/issues/1#issuecomment-1055574424)

Very good
Thanks for your reply.
When will it be released?

**Comment by djunehor** [comment]
> > Please [see](https://github.com/Shagital/adonisjs-crud-generator/issues/1#issuecomment-1055574424)
> 
> Very good Thanks for your reply. When will it be released?

No specific timeline yet. But ideally, the end of March

**Comment by a7mdragab** [comment]
> > > Please [see](https://github.com/Shagital/adonisjs-crud-generator/issues/1#issuecomment-1055574424)
> > 
> > 
> > Very good Thanks for your reply. When will it be released?
> 
> No specific timeline yet. But ideally, the end of March

Awesome
I hope you finish it ASAP
Good luck

**Comment by a7mdragab** [comment]
> > > Please [see](https://github.com/Shagital/adonisjs-crud-generator/issues/1#issuecomment-1055574424)
> > 
> > 
> > Very good Thanks for your reply. When will it be released?
> 
> No specific timeline yet. But ideally, the end of March

How can I help?

**Comment by MichaelNZ85** [comment]
> You can try converting the Js files to typescript files with separately defined types. That way, it's easy to integrate into adonisjs5

Which JS files need converting?

**Comment by a7mdragab** [comment]
Hey, Any updates?

**Comment by a7mdragab** [comment]
..

**Comment by MichaelNZ85** [comment]
Any updates? I'm happy to help if you tell me what needs doing.

**Comment by djunehor** [comment]
Hi all
Latest version that supports adonisjs5 should be ready by weekend.

**Comment by a7mdragab** [comment]
> Hi all Latest version that supports adonisjs5 should be ready by weekend.

Very nice to hear that. Will it contain a dashboard template?
thanks in advance

**Comment by djunehor** [comment]
> > Hi all Latest version that supports adonisjs5 should be ready by weekend.
> 
> Very nice to hear that. Will it contain a dashboard template? thanks in advance

I don't understand what you mean. But version 3 doesn't ship with any new feature. Basically a rewrite to make it compatible with latest adonisjs version

**Comment by djunehor** [comment]
https://github.com/Shagital/adonisjs-crud-generator/releases/tag/3.0.3

**Comment by a7mdragab** [comment]
> > > Hi all Latest version that supports adonisjs5 should be ready by weekend.
> > 
> > 
> > Very nice to hear that. Will it contain a dashboard template? thanks in advance
> 
> I don't understand what you mean. But version 3 doesn't ship with any new feature. Basically a rewrite to make it compatible with latest adonisjs version

Too thanks.
Great work.
Gooo ahead

**Comment by a7mdragab** [comment]
Can you make a simple video tutorial for it?
It would be very nice from you as you will mention all things that we may do not know about it

**Comment by djunehor** [comment]
Closing as updated version has been released
