### ISSUE TITLE
New project installation error "TypeError: ace.addCommand is not a function or "crud:init" command not found"

### ISSUE THREAD

**Issue by a7mdragab** [Shagital/adonisjs-crud-generator#3]
Hey bro,
Sorry for mentioning that.
I have created a new adonisJs project from original docs and followed the steps here, and I got the error 
```
[ error ]  "crud:init" command not found
```

Also, I have tried "Adonis/Cli" to create the project, and I got the error
```

TypeError: ace.addCommand is not a function


1 MigrationsProvider.boot
  C:\test\node_modules\@adonisjs\lucid\providers\MigrationsProvider.js:105

2 anonymous
  C:\test\node_modules\@adonisjs\fold\src\Registrar\index.js:147        

3 arrayMap
  C:\test\node_modules\lodash\lodash.js:653
  C:\test\node_modules\lodash\lodash.js:697

9 baseWrapperValue
  C:\test\node_modules\lodash\lodash.js:4429

10 LazyWrapper.lazyValue [as value]
  C:\test\node_modules\lodash\lodash.js:1901
```

May you submit a new ```template project``` repository updated!
Thanks

**Comment by djunehor** [comment]
Configure the package using `node ace @shagital/adonisjs-crud-generator`. This should update your .adonisrc.json file.

After successfully running that, then try to run the crud command again.

**Comment by a7mdragab** [comment]
> 

```
TypeError: ace.addCommand is not a function


1 MigrationsProvider.boot
  C:\test\node_modules\@adonisjs\lucid\providers\MigrationsProvider.js:105

2 anonymous
  C:\test\node_modules\@adonisjs\fold\src\Registrar\index.js:147        

3 arrayMap
  C:\test\node_modules\lodash\lodash.js:653

4 Function.map
  C:\test\node_modules\lodash\lodash.js:9622

5 interceptor
  C:\test\node_modules\lodash\lodash.js:17094

6 thru
  C:\test\node_modules\lodash\lodash.js:8859

7 anonymous
  C:\test\node_modules\lodash\lodash.js:4430

8 arrayReduce
  C:\test\node_modules\lodash\lodash.js:697

9 baseWrapperValue
  C:\test\node_modules\lodash\lodash.js:4429

10 LazyWrapper.lazyValue [as value]
  C:\test\node_modules\lodash\lodash.js:1901
```

**Comment by a7mdragab** [comment]
> > > node ace @shagital/adonisjs-crud-generator
> > 
> > 
> > [ error ] "@shagital/adonisjs-crud-generator" command not found
> 
> `node ace configure @shagital/adonisjs-crud-generator`. Note the keyword "configure"

TypeError: ace.addCommand is not a function


1 MigrationsProvider.boot
  C:\test\node_modules\@adonisjs\lucid\providers\MigrationsProvider.js:105

2 anonymous
  C:\test\node_modules\@adonisjs\fold\src\Registrar\index.js:147        

3 arrayMap
  C:\test\node_modules\lodash\lodash.js:653

4 Function.map
  C:\test\node_modules\lodash\lodash.js:9622

5 interceptor
  C:\test\node_modules\lodash\lodash.js:17094

6 thru
  C:\test\node_modules\lodash\lodash.js:8859

7 anonymous
  C:\test\node_modules\lodash\lodash.js:4430

8 arrayReduce
  C:\test\node_modules\lodash\lodash.js:697

9 baseWrapperValue
  C:\test\node_modules\lodash\lodash.js:4429

10 LazyWrapper.lazyValue [as value]
  C:\test\node_modules\lodash\lodash.js:1901

**Comment by djunehor** [comment]
> 

Can you provide steps to reproduce? Like what OS, node version, adonisjs version

**Comment by a7mdragab** [comment]
I created a new project and it worked until I reached
```Run migration node ace migration:run to create admin user and set up roles and permissions```
It gave the errors:
```
[ info ]  Upgrading migrations version from "1" to "2"
❯ error database/migrations/1655134606774_users
❯ migrating database/migrations/admin_default_role_permission                                                               
[ error ]  create table `users` (`id` int unsigned not null auto_increment primary key, `email` varchar(255) not null, `password` varchar(180) not null, `remember_me_token` varchar(255) null, `created_at` timestamp not null, `updated_at` timestamp not null) - ER_INVALID_DEFAULT: Invalid default value for 'updated_at'
    at Query.Sequence._packetToError (...\New\hello-world\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (...\New\hello-world\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (...\New\hello-world\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (...\New\hello-world\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (...\New\hello-world\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (...\New\hello-world\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (...\New\hello-world\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (...\New\hello-world\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (...\New\hello-world\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (...\New\hello-world\node_modules\mysql\lib\Connection.js:198:25)
    at ...\New\hello-world\node_modules\knex\lib\dialects\mysql\index.js:132:18       
    at new Promise (<anonymous>)
    at Client_MySQL._query (...\New\hello-world\node_modules\knex\lib\dialects\mysql\index.js:126:12)
    at executeQuery (...\New\hello-world\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_MySQL.query (...\New\hello-world\node_modules\knex\lib\client.js:146:12)
    at ...\New\hello-world\node_modules\knex\lib\execution\transaction.js:363:24      
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (...\New\hello-world\node_modules\knex\lib\execution\transaction.js:358:12)
```

I didn't understand this line, but I checked the auth middleware and it does exist.
```The api authentication method has to be functional becuase this package uses auth:api. If you want to save tokens in redis, you have to install @adonisjs/redis```

**Comment by a7mdragab** [comment]
Please make a short video to show how to get start with this.

**Comment by djunehor** [comment]
Closing this issue as it's now outdated. Please follow the step by step guide on how to setup. You can as well create a PR to add any improvement you think the package should have.
