### ISSUE TITLE
Not found model userROle

### ISSUE THREAD

**Issue by cesardmoro** [Shagital/adonisjs-crud-generator#4]
Cannot find module '/var/www/***/app/Models/Role' 

 this library you refer dont exist https://github.com/@shagital/adonisjs-acl

**Comment by cesardmoro** [comment]
Edit i fixed mysel using this: https://socket.dev/npm/package/@shagital/adonisjs-acl but you should update your docs!

**Comment by djunehor** [comment]
Thanks for bringing it to my notice. I've fixed the typo https://github.com/Shagital/adonisjs-crud-generator/releases/tag/3.0.6
